# Generated by Django 5.2 on 2025-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_blogpost_num_likes_userlogin_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
