# Generated by Django 5.2 on 2025-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_shown',
            field=models.BooleanField(),
        ),
    ]
