# Generated by Django 5.2 on 2025-05-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_alter_blogpost_is_shown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postauthor',
            options={'permissions': [('can_publish', 'Can publish post')]},
        ),
    ]
