# Generated by Django 5.2 on 2025-05-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_postauthor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('create_comment', 'Can add comment for blog-posts')]},
        ),
    ]
